"""
Router: /api/v1/persona
Repo profiling and auto-generated onboarding guide generation.

Phase 3 — Week 7 implementation.
"""

import json
import re
from collections import Counter
from pathlib import Path

from fastapi import APIRouter, HTTPException
from app.models.schemas import PersonaRequest, PersonaResponse
from app.core.repo_cloner import get_repo_root, get_repo_files, build_repo_file_tree
from app.core.llm_provider import get_llm_client, get_model_name

router = APIRouter()

# ── Language / Framework Detection ─────────────────────────────────────────────

EXTENSION_LANGUAGE_MAP = {
    ".py": "Python", ".js": "JavaScript", ".jsx": "JavaScript",
    ".ts": "TypeScript", ".tsx": "TypeScript", ".java": "Java",
    ".go": "Go", ".rs": "Rust", ".rb": "Ruby", ".php": "PHP",
    ".cs": "C#", ".cpp": "C++", ".c": "C", ".swift": "Swift",
    ".kt": "Kotlin", ".scala": "Scala", ".dart": "Dart",
}

FRAMEWORK_INDICATORS: dict[str, list[str]] = {
    "Next.js":    ["next.config.js", "next.config.mjs", "next.config.ts"],
    "React":      ["package.json"],  # checked via content
    "FastAPI":    ["requirements.txt", "pyproject.toml"],
    "Django":     ["manage.py", "settings.py"],
    "Flask":      ["requirements.txt"],
    "Express":    ["package.json"],
    "Spring":     ["pom.xml", "build.gradle"],
    "Vue":        ["vue.config.js", "nuxt.config.ts"],
    "Angular":    ["angular.json"],
    "Svelte":     ["svelte.config.js"],
}


def _detect_languages(files: list[Path]) -> list[str]:
    counter: Counter[str] = Counter()
    for f in files:
        lang = EXTENSION_LANGUAGE_MAP.get(f.suffix.lower())
        if lang:
            counter[lang] += 1
    return [lang for lang, _ in counter.most_common(5)]


def _detect_frameworks(repo_path: Path, files: list[Path]) -> list[str]:
    filenames = {f.name for f in files}
    detected: list[str] = []

    # File-presence check
    for framework, indicators in FRAMEWORK_INDICATORS.items():
        for ind in indicators:
            if ind in filenames:
                if framework in ("React", "Express", "FastAPI", "Flask"):
                    # Need content check
                    continue
                detected.append(framework)
                break

    # Content-based checks
    pkg_path = repo_path / "package.json"
    if pkg_path.exists():
        try:
            pkg = json.loads(pkg_path.read_text(encoding="utf-8", errors="replace"))
            deps = {**pkg.get("dependencies", {}), **pkg.get("devDependencies", {})}
            if "react" in deps and "Next.js" not in detected:
                detected.append("React")
            if "express" in deps:
                detected.append("Express")
            if "vue" in deps and "Vue" not in detected:
                detected.append("Vue")
        except Exception:
            pass

    req_path = repo_path / "requirements.txt"
    if req_path.exists():
        try:
            reqs = req_path.read_text(encoding="utf-8", errors="replace").lower()
            if "fastapi" in reqs:
                detected.append("FastAPI")
            if "flask" in reqs:
                detected.append("Flask")
            if "django" in reqs:
                detected.append("Django")
        except Exception:
            pass

    return list(dict.fromkeys(detected))  # deduplicate preserving order


def _read_readme(repo_path: Path) -> str:
    for name in ("README.md", "readme.md", "README.rst", "README.txt", "README"):
        p = repo_path / name
        if p.exists():
            try:
                return p.read_text(encoding="utf-8", errors="replace")[:4000]
            except Exception:
                pass
    return ""


def _summarize_tree(tree: list[dict], depth: int = 0, max_depth: int = 3) -> str:
    """Flatten the file tree into a short text summary for the LLM."""
    lines: list[str] = []
    for node in tree:
        indent = "  " * depth
        if node["type"] == "directory":
            lines.append(f"{indent}{node['name']}/")
            if depth < max_depth:
                lines.append(_summarize_tree(node.get("children", []), depth + 1, max_depth))
        else:
            lines.append(f"{indent}{node['name']}")
    return "\n".join(lines)


@router.post("/", response_model=PersonaResponse, summary="Generate repo persona")
async def generate_persona(request: PersonaRequest):
    """
    Analyze the ingested repo and generate:
      - Repo Identity Card: dominant language, frameworks, conventions, key contributors
      - Architecture overview: text-based diagram of the folder structure + module relationships
      - Onboarding guide: step-by-step "Getting Started" doc (markdown) generated by LLM
        using the README, folder structure, and key file summaries as context
    """
    repo_path = get_repo_root(request.repo_id)
    if not repo_path.exists():
        raise HTTPException(status_code=404, detail="Repo not found on disk. Please re-ingest.")

    # Static analysis
    files = get_repo_files(repo_path)
    languages = _detect_languages(files)
    frameworks = _detect_frameworks(repo_path, files)
    dominant = languages[0] if languages else "Unknown"
    readme = _read_readme(repo_path)
    tree = build_repo_file_tree(repo_path)
    tree_text = _summarize_tree(tree)

    # LLM-powered generation
    system_prompt = """You are RepoTalk Persona Generator. Given a repository's README, file tree, detected languages and frameworks, generate a JSON object with these exact keys:
- "architecture_style": one of "monolith", "monorepo", "microservices", "library", "framework", "cli-tool", "fullstack", or a short custom label.
- "conventions": 1-3 sentences about code style, naming conventions, or project structure patterns you observe.
- "key_contributors": list of up to 5 likely contributor roles (e.g. ["backend engineer", "frontend engineer"]) based on the tech stack. If the README mentions contributors, use their names.
- "onboarding_guide": A markdown onboarding guide (500-800 words) for a new developer joining this project. Include: project purpose, setup steps, key directories, how to run/test, and first contribution ideas.
- "architecture_overview": A text-based architecture diagram showing main components and their relationships using ASCII art or a simple tree-like format.

Return ONLY valid JSON. No markdown fences, no explanation."""

    user_prompt = f"""Repository: {request.repo_url}
Detected Languages: {', '.join(languages) or 'Unknown'}
Detected Frameworks: {', '.join(frameworks) or 'None detected'}

README (first 4000 chars):
{readme or '(No README found)'}

File tree:
{tree_text[:3000]}"""

    client = get_llm_client()
    model = get_model_name()

    try:
        response = await client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0.3,
            max_tokens=2048,
        )
        raw = response.choices[0].message.content or "{}"
        # Strip markdown fences if model wraps in ```json...```
        raw = re.sub(r"^```(?:json)?\s*", "", raw.strip())
        raw = re.sub(r"\s*```$", "", raw.strip())
        parsed = json.loads(raw)
    except Exception as e:
        print(f"Persona LLM generation failed: {e}")
        parsed = {}

    return PersonaResponse(
        stack=languages,
        dominant_language=dominant,
        frameworks=frameworks,
        architecture_style=parsed.get("architecture_style", "unknown"),
        conventions=parsed.get("conventions", "Could not determine conventions."),
        key_contributors=parsed.get("key_contributors", []),
        onboarding_guide=parsed.get("onboarding_guide", "Onboarding guide generation failed. Please try again."),
        architecture_overview=parsed.get("architecture_overview", tree_text[:2000]),
    )


@router.get("/{repo_id}", summary="Get cached repo persona")
async def get_persona(repo_id: str):
    """
    Return the previously generated persona for a repo.
    If the repo exists on disk, generates fresh persona data.
    """
    repo_path = get_repo_root(repo_id)
    if not repo_path.exists():
        raise HTTPException(status_code=404, detail="Repo not found on disk.")

    # Static analysis only — for cached retrieval the gateway handles DB lookup
    files = get_repo_files(repo_path)
    languages = _detect_languages(files)
    frameworks = _detect_frameworks(repo_path, files)
    dominant = languages[0] if languages else "Unknown"
    tree = build_repo_file_tree(repo_path)
    tree_text = _summarize_tree(tree)
    readme = _read_readme(repo_path)

    return {
        "repo_id": repo_id,
        "dominant_language": dominant,
        "stack": languages,
        "frameworks": frameworks,
        "tree_summary": tree_text[:2000],
        "readme_preview": readme[:1000],
    }
